### ISSUE TITLE
TypeError: The "path" argument must be of type string

### ISSUE THREAD

**Issue by jaredjgebel** [dbshanks/cra-styled-tailwind#1]
First, thanks for putting this starter out. I'd really like to get it set up locally but I'm running into an issue when I trigger the start script. I'm receiving the error below -- any thoughts? I'm running this on a Windows 10 machine.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (C:~\GitHub\styled-tailwind\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\index.js:317:13)
    at C:~\GitHub\styled-tailwind\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\index.js:335:12)
    at next (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:~\GitHub\styled-tailwind\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\index.js:317:13)
    at C:~\GitHub\styled-tailwind\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\index.js:335:12)
    at next (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:~\GitHub\styled-tailwind\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:~\GitHub\styled-tailwind\node_modules\express\lib\router\layer.js:95:5)```

**Comment by dbshanks** [comment]
Hi Jared - I am going to be making some changes to this template - Create React App recently updated React Scripts. I am going to update this package to reflect it.

If you want to try and update it on your own. 

Change React Scripts in package.json from 3.3.0 > 3.4.0 and run NPM install or update.

`  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "autoprefixer": "^9.7.4",
    "babel-plugin-macros": "^2.8.0",
    "postcss-cli": "^7.1.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
   ***** "react-scripts": "3.3.0", ***** > Change to "3.4.0"
    "styled-components": "^5.0.0",
    "tailwind.macro": "^1.0.0-alpha.10",
    "tailwindcss": "^1.1.4"
  }

``

Hope that helps. Thanks for reporting this.

**Comment by jaredjgebel** [comment]
That works! Just submitted a pull request.
